# Generated by Django 2.2.5 on 2019-10-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191001_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_record',
            name='ghost_post_id',
            field=models.CharField(blank=True, default='Not reviewed yet', max_length=500),
        ),
        migrations.AddField(
            model_name='data_record',
            name='ghost_post_uuid',
            field=models.CharField(blank=True, default='Not reviewed yet', max_length=500),
        ),
    ]
