# Generated by Django 2.2.5 on 2019-10-03 17:50

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191001_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='present_ghost_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_tags', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
