# Generated by Django 2.2.5 on 2019-10-03 18:51

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_present_ghost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='present_ghost_tags',
            name='hit_details',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
