# Generated by Django 2.2.5 on 2019-10-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191009_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_details',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
