# Generated by Django 2.2.5 on 2019-10-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191010_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_details',
            name='feature_image',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
