# Generated by Django 2.2.5 on 2019-10-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20191010_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_record',
            name='feature_image',
            field=models.URLField(default='https://images.unsplash.com/photo-1544847558-3ccacb31ee7f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80', max_length=250),
        ),
    ]
