# Generated by Django 2.2.6 on 2019-11-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_all_post_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_post_sync',
            name='publish_status',
            field=models.BooleanField(default=False),
        ),
    ]
