# Generated by Django 2.2.6 on 2019-11-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_all_post_sync_publish_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unregister_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='https://knowzone.ghostzones.ml/404/', max_length=250)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField()),
                ('visibility', models.CharField(default='public', max_length=250)),
                ('feature_image', models.URLField(max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='data_record',
            name='Not_registered_tags',
            field=models.ManyToManyField(to='myapp.Unregister_tags'),
        ),
    ]
